name: CI

on:
    pull_request:
    push:

jobs:
    build:
        runs-on: windows-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 1

            - name: Cache nuget packages
              id: cache-nuget
              uses: actions/cache@v2
              with:
                  path: ~/.nuget/packages
                  key: ${{ runner.os }}-nuget-${{ hashFiles('**/Pixeval.csproj') }}
                  restore-keys: |
                      ${{ runner.os }}-nuget-

            - name: Restore the application
              run: dotnet restore .\Pixeval\Pixeval.csproj

            - name: Build the application
              run: dotnet build .\Pixeval\Pixeval.csproj -c Release --no-restore

            - name: Publish the application
              run: dotnet publish .\Pixeval\Pixeval.csproj -p:OutDir="$PWD/publish" -c Release --no-build --no-restore

            - name: Upload a Build Artifact
              uses: actions/upload-artifact@v2
              with:
                  name: Pixeval
                  path: "./publish/*"
